materials = ["10 black-and-white photographs",
    "10 woodcut book ornaments, mounted on one sheet",
    "10-color screen print on Coventry Rag 320 gsm paper",
    "15 color slides.",
    "16 mm print transferred to Digital Betacam, black and white, sound, 10 minutes",
    "16mm animation cell",
    "18 color slides.",
    "29 Fuji Crystal archive prints",
    "3-color Risograph print",
    "3-color lithograph",
    "35 mm color slide",
    "35 mm negatives",
    "35mm color slide",
    "38 color slides.",
    "4 carbon copies",
    "4 color slides.",
    "54 color slides.",
    "6 gelatin silver prints mounted on board",
    "6 gelatin silver prints, mounted on board",
    "9 color slides mounted on board",
    "A black and white photograph.",
    "Acrylic and acqua-oil on canvas",
    "Acrylic and dry pigment on canvas",
    "Acrylic and gouache on paper",
    "Acrylic and ink",
    "Acrylic and ink on paper",
    "Acrylic and oil crayon on paper",
    "Acrylic and oil on paper",
    "Acrylic and wax on paper",
    "Acrylic ink and acrylic paint on paper",
    "Acrylic on canvas",
    "Acrylic on linen",
    "Acrylic on paper",
    "Acrylic on paper mounted on board",
    "Acrylic on powdered pigment print, A/P III",
    "Acrylic on wood",
    "Acrylic, gouache, pen, pencil, paper, fabric, glue, and thread",
    "Album Leaf: ink and color on silk",
    "Album leaf, ink on paper",
    "Album leaf: ink and color on paper",
    "Album leaf: ink and colors on paper",
    "Album leaf: ink, colors, and gold on paper",
    "Albumen",
    "Albumen print",
    "Albumen print mounted on cardboard",
    "Albumin print",
    "Albumin print from a waxed paper negative",
    "Amber seal",
    "Announcement card. Printed black on white card stock.",
    "Announcement card. Printed black on white card stock. Printed on both sides.",
    "Aquatint",
    "Aquatint and drypoint",
    "Aquatint on paper",
    "Aquatint with overlaid hosho paper coated with beeswax",
    "Archival Piezography print",
    "Archival digital c-print, Formica",
    "Archival inkjet print",
    "Archival pigment print",
    "Archival pigment print on paper",
    "Archival pigment print on rag paper",
    "Archival pigment print on rag paper, edition 2/",
    "Archival pigment print on rag paper, edition 6/",
    "Archival pigment prints",
    "Artist book. Unpaginated.",
    "Artist book; 8 pages.",
    "Artist periodical. Wrappers. Staple bound. Unpaginated.",
    "Artist's book",
    "Artist's book.",
    "Artist's book. Wrappers. Corner stapled. Unpaginated.",
    "Artist's book. Wrappers. Staple bound. Text in Polish and English. Unpaginated.",
    "Artist's book. Wrappers. Staple bound. Unpaginated.",
    "Artist's book. Wrappers. Unpaginated.",
    "Artist's book: graphite smudged covers; in plastic sleeve; edition of",
    "Artists' book",
    "Artists' publication",
    "Audio magnetic tape",
    "Bamboo seal",
    "Black and white etching",
    "Black and white photograph",
    "Black and white photograph mounted on aluminum",
    "Black and white print",
    "Black glazed pottery",
    "Black offset print and silkscreen on newsprint",
    "Black-and-white Polaroid picture (performance still)",
    "Black-and-white lithograph",
    "Black-and-white photograph",
    "Black-and-white photograph, graphite and ink on the verso",
    "Blue pencil on paper",
    "Blueprint",
    "Bronze",
    "Bronze seal",
    "Bronze, consecration materials",
    "C-Print",
    "C-print",
    "C-print on Fuji Crystal Archive paper",
    "C-print, ed. 3/",
    "C-print, edition 1/",
    "Cabro print",
    "Calligraphy scroll",
    "Carved wood",
    "Carved, gessoed, painted and varnished wood",
    "Casein on paper",
    "Cast aluminum",
    "Cast bronze",
    "Cast paper pulp with feathers",
    "Ceramic",
    "Ceramic seal",
    "Charcoal and fruit juice fixative on barkcloth",
    "Charcoal on paper",
    "Charcoal, Graphite, oil based pigments on paper",
    "Charcoal, fruit juice fixative, and fruit juice ink on barkcloth",
    "Charcoal, fruit juice ink, and mud on barkcloth",
    "Charcoal, graphite, bone black, acrylic medium base on BFK Rives paper",
    "Charcoal, graphite, bone black, acrylic on BFK Rives paper",
    "China ink on paper",
    "Chromogenic color print",
    "Chromogenic color print (A/P)",
    "Chromogenic print",
    "Chromogenic prints",
    "Cibachrome print",
    "Cizhou ware, stoneware",
    "Collage",
    "Collage and acrylic on Yupo paper",
    "Collage mounted on board",
    "Collage, rubber stamp, marker, and Xerox on paper",
    "Collaged envelope",
    "Collaged monotype",
    "Color Polaroid",
    "Color Polaroid picture (performance still)",
    "Color and starch on cotton cloth",
    "Color and varnish on paper",
    "Color aquatint",
    "Color aquatint on paper",
    "Color etching",
    "Color intaglio",
    "Color lithograph",
    "Color offset lithograph",
    "Color offset print",
    "Color pencil and marker on tracing paper",
    "Color pens and colored pencil on paper",
    "Color pens on paper",
    "Color photograph",
    "Color photograph (2 copies)",
    "Color photograph of a drawing",
    "Color photograph on photocopy",
    "Color postcard",
    "Color serigraph",
    "Color silkscreen",
    "Color spit bite aquatint",
    "Color spit bite aquatint with aquatint",
    "Color woodblock print",
    "Color woodblock printing",
    "Color woodblock prints",
    "Color woodcut",
    "Color woodcut (empty folio)",
    "Color woodcut and folio",
    "Colored pencil and watercolor on paper",
    "Colored pencil on archival paper",
    "Colored pencil on paper",
    "Colors on cotton",
    "Colors on cotton, mounted on a wooden frame",
    "Colors on cotton, silk mount, wooden hanging rod",
    "Colors on cotton, silk mount, wooden hanging rods",
    "Colors on cotton, silk mount, wooden hanging rods, one bronze knob",
    "Colors on silk, with brocade, wood and silver knobs",
    "Computer generated drawing on paper",
    "Computer printout with solvent transfer and hand-drawn details",
    "Conte on paper",
    "Copper",
    "Cow dung and acrylic on raw canvas",
    "Crayon on paper",
    "DVD",
    "Digital Betacam videotape: color; sound",
    "Digital C-type photograph",
    "Digital chromogenic print",
    "Digital image mounted on Masonite",
    "Digital inkjet print",
    "Digital pigment print",
    "Digital print",
    "Digital print on archival rag paper, ed. 16/",
    "Digital print on semi-gloss premium photo paper (poster)",
    "Digital print on semi-gloss premium photo paper (poster); vinyl high-gloss UV sticker",
    "Drypoint",
    "Drypoint etching",
    "Duraflex print",
    "Dye diffusion transfer print",
    "Ektacolor print",
    "Engobe, stoneware",
    "Engraving",
    "Engravings",
    "Epson UltraChrome k# Inkjet print",
    "Etching",
    "Etching and aquatint",
    "Etching and drypoint",
    "Etching and engraving",
    "Etching, aquatint and drypoint",
    "Etching; AP",
    "Etchings on Rives heavyweight paper",
    "Exhibition catalog",
    "Exhibition catalog, unpaginated.",
    "Exhibition catalog.",
    "Fan painting: ink and color on gold paper",
    "Fan painting: ink and color on paper",
    "Fan painting: ink on paper",
    "Fan; peach-shaped: ink, colors, and gold on paper",
    "Fiber-based gelatin silver print",
    "Flyer. Photocopy. Printed black on white paper.",
    "Flyer. Printed black on white paper.",
    "Folding screen with paint (acrylic and/or gouache?), ink, and graphite on paper and newspaper with collage and color print reproductions.",
    "Framed color photograph",
    "Full color woodblock print",
    "Full color woodblock print with metal accents",
    "Full color woodblock print, gold and silver on kimono patterns.",
    "Full color woodblock printing",
    "Full color woodblock printing, alum applied on surface.",
    "Full color woodblock printing, embossing applied in areas.",
    "Full color woodblock printing, embossing in areas.",
    "Full color woodblock printing, embossing in parts of kimono.",
    "Full color woodblock printing, embossing on waves.",
    "Full color woodblock printing, gold and silver",
    "Full color woodblock printing, mica background",
    "Full color woodblock printing, silver and gold.",
    "Full color woodblock printing.",
    "Full-color woodblock print with mica background",
    "Gelatin Silver Print",
    "Gelatin Silver print",
    "Gelatin silver print",
    "Gelatin silver print mounted on board",
    "Gelatin silver prints",
    "Gilt bronze seal",
    "Glass",
    "Glass beads strung on cotton",
    "Glass with rayon flocking",
    "Glazed ceramic",
    "Glazed ceramic vessel",
    "Glazed ceramic with gold",
    "Gold toned silver print",
    "Gold with copper or bronze backing",
    "Gold-toned printing out paper",
    "Gouache and collage on paper",
    "Gouache and graphite on paper",
    "Gouache and pencil on paper",
    "Gouache and pencil on paper.",
    "Gouache on paper",
    "Gouache, watercolor, and gold border on vellum",
    "Graphite and acrylic on canvas",
    "Graphite and acrylic on embossed paper",
    "Graphite and colored pencil on paper",
    "Graphite and watercolor on paper",
    "Graphite and watercolor on rice paper",
    "Graphite on paper",
    "Graphite on vellum",
    "Graphite, ink, and watercolor on paper",
    "Ground mineral pigment on cotton",
    "HD video, color, silent",
    "Hand-built, englobe, colorants, stoneware",
    "Hand-built, englobe, stoneware",
    "Hand-colored artist's book",
    "Hand-colored etching",
    "Hand-colored woodblock print",
    "Hand-dyed, hand-woven linen",
    "Handwritten text in pencil on paper.",
    "Hanging scroll",
    "Hanging scroll in wooden box",
    "Hanging scroll:",
    "Hanging scroll: ink and color on paper",
    "Hanging scroll: ink and color on silk",
    "Hanging scroll: ink and colors on paper",
    "Hanging scroll: ink and colors on silk",
    "Hanging scroll: ink and light colors on paper",
    "Hanging scroll: ink and light colors on silk",
    "Hanging scroll: ink and on paper",
    "Hanging scroll: ink on paper",
    "Hanging scroll: ink on satin",
    "Hanging scroll: ink on silk",
    "Hanging scroll: inks and colors on paper",
    "Hanging scroll; ink and color on paper",
    "Hanging scroll; ink and light color on silk",
    "Holographic letter with envelope. Blue ball point pen on white lined paper.",
    "Holographic letter with envelope. Blue ball point pen on white paper.",
    "Holographic letter. Black ball point pen on aerogramme.",
    "Holographic letter. Black ball point pen on photocopy.",
    "Holographic letter. Black ball point pen on postcard.",
    "Holographic letter. Black ball point pen on white card stock.",
    "Holographic letter. Black ball point pen on white paper.",
    "Holographic letter. Black felt pen on color postcard.",
    "Holographic letter. Black felt pen on postcard.",
    "Holographic letter. Black felt pen on white card stock.",
    "Holographic letter. Black felt pen on white paper.",
    "Holographic letter. Blue ball point pen on color postcard.",
    "Holographic letter. Blue ball point pen on postcard.",
    "Holographic letter. Blue ball point pen on postcard. 1 rubber stamp.",
    "Holographic letter. Blue ball point pen on white card stock.",
    "Holographic letter. Blue ball point pen on white paper.",
    "Holographic letter. Blue felt pen on white paper.",
    "Holographic letter. Draft copy. Blue ball point pen on lined white paper.",
    "Hydrocal",
    "Incised palm-leaf darkened with charcoal dust and washes of color",
    "India ink on Dura-Lar",
    "India ink on paper",
    "Ink and color on board",
    "Ink and color on paper",
    "Ink and color on silk",
    "Ink and colors on paper",
    "Ink and crayon on paper",
    "Ink and gold on brown paper",
    "Ink and gold on paper",
    "Ink and gouache on paper",
    "Ink and graphite on paper",
    "Ink and opaque watercolor on paper",
    "Ink and pencil on paper5",
    "Ink and watercolor on paper",
    "Ink on Japanese paper",
    "Ink on board",
    "Ink on gazelle skin",
    "Ink on paper",
    "Ink on vellum",
    "Ink, color wash and gold on gazelle skin",
    "Ink, color wash, and gold on paper",
    "Ink, opaque watercolor, and gold on paper",
    "Inkjet on inkjet medium",
    "Inkjet print",
    "Intaglio",
    "Iron",
    "Ivory",
    "Ivory seal",
    "Jade seal",
    "Letter with envelope. Black typescript on white paper.",
    "Letter with envelope. Photocopy. Printed black on white paper.",
    "Letter. Black ball point pen on photocopy.",
    "Letter. Black felt pen on photocopy.",
    "Letter. Black typescript and black ball point pen on The Richard Demarco Gallery Ltd stationery.",
    "Letter. Black typescript and black ball point pen on white paper.",
    "Letter. Black typescript and blue ball point pen on white paper.",
    "Letter. Black typescript on Alice M. Denney stationery.",
    "Letter. Black typescript on Art and Artists stationery.",
    "Letter. Black typescript on Artforum stationery.",
    "Letter. Black typescript on Australia Council stationery.",
    "Letter. Black typescript on California College of Arts and Crafts stationery.",
    "Letter. Black typescript on California Institute of Arts stationery.",
    "Letter. Black typescript on California Institute of the Arts stationery.",
    "Letter. Black typescript on California State College, Bakersfield stationery.",
    "Letter. Black typescript on Everson Museum of Art stationery.",
    "Letter. Black typescript on Gallery Paule Anglim stationery.",
    "Letter. Black typescript on Houston Fine Art Press stationery. Unpaginated. 2 pages.",
    "Letter. Black typescript on ICI stationery.",
    "Letter. Black typescript on John Simon Guggenheim Memorial Foundation stationery.",
    "Letter. Black typescript on La Mamelle stationery.",
    "Letter. Black typescript on Montana State University stationery.",
    "Letter. Black typescript on Mundus Artium stationery.",
    "Letter. Black typescript on Nova Scotia College of Art and Design stationery.",
    "Letter. Black typescript on Richmond Art Center stationery.",
    "Letter. Black typescript on San Francisco Art Institute stationery.",
    "Letter. Black typescript on San Francisco Chronicle stationery.",
    "Letter. Black typescript on San Francisco Museum of Modern Art stationery.",
    "Letter. Black typescript on San Francisco Redevelopment Agency stationery.",
    "Letter. Black typescript on Santa Barbara Museum of Art stationery.",
    "Letter. Black typescript on Stedelijk Museum stationery.",
    "Letter. Black typescript on The Richard Demarco Gallery Ltd stationery.",
    "Letter. Black typescript on University of California, Berkeley stationery.",
    "Letter. Black typescript on University of California, Los Angeles stationery.",
    "Letter. Black typescript on University of California, San Diego stationery.",
    "Letter. Black typescript on University of California, Santa Barbara stationery.",
    "Letter. Black typescript on aerogramme.",
    "Letter. Black typescript on blue paper.",
    "Letter. Black typescript on documenta 5 stationery.",
    "Letter. Black typescript on photocopy.",
    "Letter. Black typescript on postcard.",
    "Letter. Black typescript on white card stock.",
    "Letter. Black typescript on white paper.",
    "Letter. Black typescript on white paper. 1 rubber stamp.",
    "Letter. Blue ball point pen on photocopy.",
    "Letter. Carbon copy. Printed black on MOCA stationery.",
    "Letter. Carbon copy. Printed black on Richmond Art Center stationery.",
    "Letter. Carbon copy. Printed black on graph paper.",
    "Letter. Carbon copy. Printed black on orange paper.",
    "Letter. Carbon copy. Printed black on white paper.",
    "Letter. Carbon copy. Printed black on white paper. 2 copies.",
    "Letter. Carbon copy. Printed black on yellow paper.",
    "Letter. Photocopy. Printed black on white paper.",
    "Letter. Printed black on The University of British Columbia stationery.",
    "Letter. Printed black on yellow paper.",
    "Letterpress print",
    "Linocut",
    "Lithograph",
    "Low fire ceramic with airbrushed China paint",
    "Lucite cut on rice paper",
    "Mail art. Offset; black on white cardstock.",
    "Marker on color postcard",
    "Marker on paper",
    "Metal",
    "Mimeograph copy",
    "Mixed media",
    "Mixed media assemblage",
    "Mixed media collage",
    "Mixed media in plastic box with offset on paper label",
    "Mixed media on paper",
    "Mixed media on wood",
    "Monoprint",
    "Monotype",
    "Monotype and gelatin silver print",
    "Musical score",
    "Natural pigment on barkcloth",
    "Offset lithograph",
    "Offset lithography",
    "Offset lithography on cardstock",
    "Offset lithography on cardstock (2-sided)",
    "Offset lithography on glossy paper",
    "Offset lithography on paper",
    "Offset on card stock",
    "Offset print",
    "Offset print on paper",
    "Offset print, two-sided",
    "Offset printing on paper",
    "Oil and acrylic on canvas",
    "Oil on Masonite",
    "Oil on board",
    "Oil on canvas",
    "Oil on canvas and rake",
    "Oil on canvas board",
    "Oil on canvas, rake and glass bowl",
    "Oil on linen",
    "Oil on panel",
    "Oil on paper",
    "Oil on tintype",
    "Oil pastel on paper",
    "Paint on board",
    "Paint on found paper",
    "Painted wood",
    "Paper",
    "Paper collage",
    "Paper maché and wire",
    "Pastel on paper",
    "Pencil and ink on paper",
    "Pencil and marker on paper",
    "Pencil and watercolor on paper46",
    "Pencil on paper",
    "Pencil on vellum",
    "Pencil on vellum or tissue paper (varies)",
    "Periodical, paperbound, black and white",
    "Permanent pigment print",
    "Photo etching",
    "Photo silkscreen",
    "Photocopy",
    "Photocopy of newspaper clipping",
    "Photocopy on paper",
    "Photocopy, 1 of 2 pages",
    "Photocopy, 2 of 2 pages",
    "Photocopy. 12 pages.",
    "Photocopy. Corner stapled. Printed black on white paper. 2 pages.",
    "Photocopy. Printed black on white paper.",
    "Photograph printed on watercolor paper",
    "Photographic print, mounted on aluminum",
    "Pigment print",
    "Platinum print",
    "Plexiglass",
    "Polacolor",
    "Polacolor ER",
    "Polacolor Type",
    "Polaroid",
    "Polaroid Polacolor ER Land Film",
    "Porcelain with underglaze cobalt decor, transparent overglaze",
    "Porcelain with underglaze cobalt decoration, transparent overglaze",
    "Postcard",
    "Print",
    "Print on paper",
    "Print with wooden type",
    "Raffia palm fiber",
    "Risograph print",
    "Risograph print, two copies",
    "Risograph prints",
    "Risograph prints, two copies",
    "Screen print on archival paper",
    "Screen print on paper (poster)",
    "Selenium toned gelatin silver print",
    "Selenium-toned gelatin silver print",
    "Serigraph",
    "Silk",
    "Silkscreen",
    "Silkscreen on linen",
    "Silverpoint and colored pencil on paper",
    "Soot on envelope and cardboard",
    "Stenciled silkscreen",
    "Stone seal",
    "Stoneware",
    "Super-8. 3 minutes. 24 frames per second?",
    "Tempera on board",
    "Tempera on paper5",
    "Tempera on wood",
    "Three color woodblock printing",
    "Three color woodblock printing(Grey, blue, and orange)",
    "Toned gelatin silver print",
    "Two glass vitrines, wood, cardboard, paper, glass funnel, and stamping paint",
    "Typewritten text and ink on stationery",
    "Typewritten text and marker on stationery",
    "Typewritten text and rubber stamp on photocopied paper, 3-hole punched",
    "Typewritten text on paper",
    "Typewritten text on paper.",
    "Typewritten text on stationery",
    "Uncoated, high-polished bronze sculpture, base, pedestal, two framed photographs",
    "Undetermined",
    "Various media",
    "Video",
    "Video tape.",
    "Videotape",
    "Videotape transferred to Digital Betacam; black and white, sound, 60 minutes",
    "Vintage gelatin silver print",
    "Watercolor",
    "Watercolor and ink on paper",
    "Watercolor and pen on paper",
    "Watercolor on Arches paper",
    "Watercolor on graph paper",
    "Watercolor on paper",
    "Watercolor on silk",
    "Wood",
    "Wood block print on paper",
    "Wood seal",
    "Woodblock print",
    "Woodblock print on cotton (20th century print from older woodblocks)",
    "Woodcut",
    "Zinc lithograph on canary paper",
    "a: Woodblock print on yellow synthetic silk; b: woodblock print on cotton (20th century print from older woodblocks)",
    "a: marker on paper b: marker on envelope with postmark and postage stamp",
    "acrylic and mixed media on paper",
    "acrylic on canvas",
    "acrylic on linen",
    "acrylic on paper",
    "acrylic on wood",
    "album leaf: ink and light color on paper",
    "album leaf: ink on silk",
    "album: ink and color on paper",
    "album: ink and colors on paper",
    "albumen",
    "albumen print",
    "albumen print from wet-plate collodion negative",
    "albumen print from wet-plate collodion negative, linen-backed3",
    "albumen, linen backed",
    "albumen, linen-backed",
    "aquatint",
    "aquatint with overlaid hosho paper coated with beeswax",
    "artist catalog",
    "artist periodical: cardboard, ink, paper",
    "artist's book",
    "artist's book; 10 pages",
    "audio tape",
    "autochrome",
    "barkcloth, charcoal, fruit juice ink",
    "beaten barkcloth, charcoal or fruit juice ink and/or fixative, soaked in mud",
    "black & white photograph",
    "black and white photograph",
    "black and white photograph with caption",
    "black and white photograph, five copies",
    "black and white pigment print",
    "black crayon on paper",
    "black-and-white contact sheet",
    "black-and-white contact sheet, marker on verso",
    "black-and-white negative",
    "black-and-white offset printing on paper",
    "black-and-white photo mounted on board",
    "black-and-white photograph",
    "black-and-white photograph on black cardboard, three-hole punched",
    "black-and-white photograph with blue marker on verso",
    "black-and-white photograph with marker",
    "black-and-white photograph with press type; graphite on verso",
    "black-and-white photograph, graphite on verso",
    "black-and-white photograph, ink and stamp on verso",
    "black-and-white photograph, ink, marker and rubber stamp in blue ink on verso",
    "black-and-white photograph, label mounted on verso",
    "black-and-white photograph, three copies",
    "black-and-white photograph, two copies",
    "black-and-white photograph, two exposures",
    "black-and-white photograph, with graphite and stamp mark in black ink on verso",
    "black-and-white postcard, two-sided",
    "black-and-white transparency",
    "blue ink and typewritten text on paper",
    "blue marker on photocopy",
    "blueprint",
    "bronze",
    "brush and ink on paper",
    "brush, ink and color on paper",
    "cabinet card, albumen print",
    "carbon print",
    "ceramic",
    "chalk on black paper",
    "chalk on paper",
    "charcoal",
    "charcoal on paper",
    "cibachrome",
    "cibachrome print",
    "cinema photograph24",
    "cliche-verre",
    "coated collotype",
    "collage and handwritten text on paper, in plastic sleeve",
    "collotype",
    "collotype coated with shellac or gelatin",
    "color 35mm slide",
    "color Polaroid",
    "color and ink on paper",
    "color and varnish on paper",
    "color etching",
    "color etching and aquatint",
    "color litho",
    "color lithograph",
    "color offset printing on paper",
    "color offset printing on paper, two-sided",
    "color offset printing on paper, with offset printing and mailing label on verso",
    "color photocopy",
    "color photograph",
    "color photograph (Polaroid)",
    "color photograph, three copies",
    "color photograph, two copies",
    "color print",
    "color silkscreen",
    "color transparency",
    "color transparency, three copies",
    "color transparency, two copies",
    "color woodblock print",
    "color woodcut",
    "copper plate etchings on Twinrocker paper",
    "crayon on paper",
    "daguerreotype",
    "drawing",
    "drawing on paper",
    "drypoint",
    "dye transfer color photograph",
    "dye transfer print",
    "dye transfer, color photograph",
    "earthenware and pigment",
    "engraving",
    "etching",
    "etching and aquatint",
    "etching and drypoint",
    "etching with aquatint",
    "etching with aquatint (portfolio of eight prints)",
    "etching with drypoint",
    "etching with engraving",
    "etching, aquatint",
    "etching, drypoint",
    "etching, reinforced with aquatint",
    "fan mounted as hanging scroll: ink and color on gold paper",
    "fan painting: ink and color on paper",
    "fan painting: ink and colors on paper",
    "fan painting: ink on gold paper",
    "fan paintings: ink and color on paper",
    "found paper, string, soot, and spit",
    "found photo and handwritten text on paper, in plastic sleeve",
    "full color woodblock print",
    "gelatin silver chloride print",
    "gelatin silver print",
    "gelatin silver print on resin coated paper",
    "gelatin silver print, mounted on board",
    "gelatin silver prints",
    "gelatin silver prints, mounted on board",
    "gilt bronze",
    "glass",
    "gold offset print on black paper",
    "gold pencil on red paper",
    "gouache",
    "gouache and gold on paper",
    "gouache on paper",
    "graphite and ink on file folder",
    "graphite and sanguine on paper",
    "graphite on paper",
    "graphite pencil",
    "handscroll: ink and color on paper",
    "handscroll: ink and colors on paper",
    "handscroll: ink on paper",
    "handwritten on paper",
    "hanging scroll",
    "hanging scroll: ink and color on paper",
    "hanging scroll: ink and color on satin",
    "hanging scroll: ink and color on silk",
    "hanging scroll: ink and colors on paper",
    "hanging scroll: ink and colors on silk",
    "hanging scroll: ink and light colors on silk",
    "hanging scroll: ink on paper",
    "hanging scroll: ink on satin",
    "hanging scroll: ink on silk",
    "incised palm leaf darkened with charcoal dust and washes of color",
    "ink and color on paper",
    "ink and color on silk",
    "ink and color on silk mounted on tissue",
    "ink and color wash on paper",
    "ink and colors on paper",
    "ink and gouache on paper",
    "ink and graphite on paper",
    "ink and light color on paper",
    "ink and typewritten text on paper",
    "ink and typewritten text on yellow paper (carbon copy), two-hole punched",
    "ink and wash on paper",
    "ink and watercolor on paper",
    "ink on black-and-white postcard with airmail stamp, postmark and postage stamp",
    "ink on color postcard with airmail stamp, postmark and postage stamp",
    "ink on color postcard with airmail stamp, postmark and two postage stamps",
    "ink on color postcard with postmark and postage stamp",
    "ink on file folder",
    "ink on paper",
    "ink on paper with some red gouache",
    "ink on paper, two-sided",
    "ink on silk",
    "ink, gouache, and gold on ivory",
    "ink, gouache, and gold on mica",
    "ink, gouache, and gold on paper",
    "ink, gouache, gold, and silver on paper",
    "ink, gouache, gold, and varnish on paper",
    "ink, watercolor on paper",
    "inkjet on vellum, ink",
    "intaglio",
    "kodalith",
    "letterpress",
    "lichtdrucke print (photostat)",
    "linocut",
    "linocut on computer paper, 2 copies",
    "lithograph",
    "lithograph on newsprint",
    "magazine clippings under mat with handwritten text, mounted on board",
    "magazine clippings under mat, mounted on board",
    "marble",
    "marker on file folder",
    "marker on photocopy with collage elements",
    "matte gelatin silver chloride print",
    "metal",
    "mezzotint",
    "mezzotint on paper",
    "mixed media",
    "mixed media assemblage",
    "mixed media collage",
    "mixed media collage on paper with handwritten text, in plastic sleeve",
    "mixed media installation with 30 components",
    "mixed media on canvas",
    "mixed media on paper",
    "monoprint",
    "monotype",
    "natural pigment on barkcloth",
    "natural pigments on barkcloth",
    "natural rubber",
    "newspaper clipping",
    "offset lithograph",
    "offset lithograph (film poster)",
    "offset lithograph on paper",
    "offset lithographs on paper",
    "offset lithography on paper",
    "offset lithography on paper, three-hole punched4",
    "offset print",
    "offset print on paper",
    "offset printing and felt-tip pen on card",
    "offset printing in red on paper",
    "offset printing on paper",
    "offset printing on paper, three copies",
    "offset printing on paper, two copies",
    "offset printing on paper, two-sided",
    "offset printing on paper, with offset printing and mailing label on verso",
    "oil and enamel on canvas",
    "oil and wash on leather panel",
    "oil on Masonite",
    "oil on board",
    "oil on canvas",
    "oil on linen",
    "oil on maple, and silver plated trophies",
    "oil on panel",
    "oil on paper",
    "oil on plywood",
    "oil on tintype",
    "oil on wood",
    "oil on wood panel",
    "one of five photographic panels",
    "paint on fabric",
    "paint on oil cloth on paper",
    "painted steel",
    "painted wood",
    "paper",
    "paperback book",
    "pastel on paper",
    "pen and ink",
    "pen and ink on paper",
    "pencil",
    "pencil on graph paper",
    "pencil on paper",
    "pencil on vellum",
    "photo screenprint",
    "photo-offset accordion-fold book, 7 pages",
    "photo-offset lithograph",
    "photocopy",
    "photocopy on paper",
    "photocopy on paper with handwritten notations",
    "photocopy on pink paper",
    "photocopy with collage element",
    "photocopy with collage elements",
    "photocopy, four pages",
    "photocopy, three copies",
    "photocopy, three pages",
    "photocopy, three pages, stapled",
    "photocopy, three-hole punched",
    "photocopy, three-hole punched, two pages",
    "photocopy, two copies",
    "photocopy, two pages",
    "photocopy, two-sided",
    "photograph",
    "photograph mounted on card",
    "photographic reproduction on paper",
    "photogravure",
    "pink tinted albumen",
    "plant fiber and beads",
    "plaster",
    "platinum print",
    "postcard",
    "poster",
    "red crayon on paper",
    "salt print",
    "sandstone",
    "sanguine",
    "sanguine on paper",
    "screen print",
    "screenprint",
    "screenprint on 2 cotton t-shirts, 1 large, 1 extra large",
    "screenprint on computer paper",
    "selenium toned gelatin silver print",
    "silkscreen",
    "silkscreen on Plexiglas",
    "silkscreen on canvas paper",
    "silkscreen on paper",
    "silkscreen on rice paper",
    "silver gelatin print",
    "silver print",
    "soft metal engraving",
    "soft metal engraving, hand coloring",
    "stainless steel",
    "steel",
    "stone",
    "tempera on gessoed pine board",
    "tempera on paper",
    "thermogram and pencil",
    "tintype",
    "toned gelatin silver print",
    "tracing paper and gold pencil on paper, with gold pencil on offset printed label on black paper cover, thread-bound",
    "two-color silkscreen",
    "typewritten on paper",
    "typewritten text and ink on Newport Harbor Art Museum stationery",
    "typewritten text and ink on embossed stationery",
    "typewritten text and ink on paper",
    "typewritten text and ink on paper, three-hole punch",
    "typewritten text and ink on stationery",
    "typewritten text and offset printing on paper with stamp mark in black ink",
    "typewritten text and offset printing on paper with stamp mark in black ink, three copies",
    "typewritten text and paste-up graphics and photographs on paper",
    "typewritten text on Richmond Art Center stationery (carbon copy), two-hole punched",
    "typewritten text on light orange paper (carbon copy)",
    "typewritten text on paper",
    "typewritten text on paper (carbon copy)",
    "typewritten text on paper (carbon copy), two-hole punched",
    "typewritten text on yellow paper",
    "typewritten text on yellow paper (carbon copy), two-hole punched",
    "typewritten text on yellow paper, two-hole punched",
    "typewritten text, graphite, and masking tape on paper",
    "vacuum formed polyvinyl",
    "video",
    "vintage cibachrome print",
    "vintage gelatin silver print",
    "vintage gelatin silver print mounted on board",
    "watercolor",
    "watercolor and graphite on paper",
    "watercolor and ink on chiffon pur",
    "watercolor and ink on paper",
    "watercolor and pencil on paper",
    "watercolor on paper",
    "watercolor on rag paper",
    "watercolor woodcut",
    "white illustration board, black and white photographs, typewritten text",
    "white stoneware with cobalt decoration underneath clear glaze",
    "wood",
    "wood and metal",
    "wood engraving",
    "woodblock",
    "woodblock print",
    "woodblock print on paper",
    "woodburytype",
    "woodcut",
]